### ISSUE TITLE
grid-status.py returned failed: JobEventLog not initialized

### ISSUE THREAD

**Issue by matthewfeickert** [Snakemake-Profiles/htcondor#21]
Do you know the last version of `snakemake`, `htcondor`, and `python-htcondor` that worked together? I'm trying to do a hello world example with a profile generated by

```
cookiecutter --output-dir .profiles/ --no-input gh:Snakemake-Profiles/htcondor profile_name=lxbatch htcondor_log_dir=$HOME/.condor_jobs
```

and a trivial Snakemake rule

```snakefile
rule hello_lxbatch:
    output:
        "local_hello.txt"
    shell:
        """
        echo "hello hello $(date)" > {output}
        """
```

then fails when

```
snakemake --profile .profiles/lxbatch --snakefile workflow/Snakefile --verbose --cores 1 --printshellcmds hello_lxbatch
```

is run as the log file

https://github.com/Snakemake-Profiles/htcondor/blob/fd097135bf3336248ed259e142ee22a7a974c729/%7B%7Bcookiecutter.profile_name%7D%7D/grid-submit.py#L24

isn't getting created (the full log is below).

<details>
<summary>Details:</summary>

```console
$ snakemake --profile .profiles/lxbatch --snakefile workflow/Snakefile --verbose --cores 1 --printshellcmds hello_lxbatch

Using profile .profiles/lxbatch for setting default command line arguments.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 5000
Singularity containers: ignored
Job stats:
job              count
-------------  -------
hello_lxbatch        1
total                1

Resources before job selection: {'_cores': 9223372036854775807, '_nodes': 5000}
Ready jobs (1)
Select jobs to execute...
Using greedy selector because only single job has to be scheduled.
Selected jobs (1)
Resources after job selection: {'_cores': 9223372036854775806, '_nodes': 4999}

[Fri Apr  5 02:13:19 2024]
rule hello_lxbatch:
    jobid: 0
    reason: Rules with neither input nor output files are always executed.
    resources: mem_mb=1000, mem_mib=954, disk_mb=1000, disk_mib=954, tmpdir=<TBD>


        echo "hello hello $(date)"
        
Jobscript:
#!/bin/bash
# properties = {"type": "single", "rule": "hello_lxbatch", "local": false, "input": [], "output": [], "wildcards": {}, "params": {}, "log": [], "threads": 1, "resources": {"mem_mb": 1000, "mem_mib": 954, "disk_mb": 1000, "disk_mib": 954, "tmpdir": "<TBD>"}, "jobid": 0, "cluster": {}}

set -e

echo "hostname:"
hostname -f

cd /afs/cern.ch/work/f/feickert/snakemake-lxplus-example && /afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/bin/python3.11 -m snakemake --snakefile '/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/workflow/Snakefile' --target-jobs 'hello_lxbatch:' --allowed-rules 'hello_lxbatch' --cores 'all' --attempt 1 --force-use-threads  --resources 'mem_mb=1000' 'mem_mib=954' 'disk_mb=1000' 'disk_mib=954' --wait-for-files '/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.snakemake/tmp.95w96k2q' --force --keep-target-files --keep-remote --max-inventory-time 0 --nocolor --notemp --no-hooks --nolock --ignore-incomplete --rerun-triggers 'input' 'mtime' 'software-env' 'code' 'params' --skip-script-cleanup  --conda-frontend 'mamba' --wrapper-prefix 'https://github.com/snakemake/snakemake-wrappers/raw/' --printshellcmds  --latency-wait 5 --scheduler 'ilp' --scheduler-solver-path '/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/bin' --default-resources 'mem_mb=max(2*input.size_mb, 1000)' 'disk_mb=max(2*input.size_mb, 1000)' 'tmpdir=system_tmpdir' --mode 2 && exit 0 || exit 1

Submitted job 0 with external jobid '0_a6334115-55b6-4993-8a83-0e1997b22829_Submitted 1 jobs into cluster 11646735,0 :'.
04/05/24 02:13:29 ReadUserLog: Failed to open /afs/cern.ch/user/f/feickert/.condor_jobs/0_a6334115-55b6-4993-8a83-0e1997b22829/condor.log
04/05/24 02:13:29 FileModifiedTrigger( /afs/cern.ch/user/f/feickert/.condor_jobs/0_a6334115-55b6-4993-8a83-0e1997b22829/condor.log ): open() failed: No such file or directory (2).
Cluster status command .profiles/lxbatch/grid-status.py returned failed: JobEventLog not initialized.  Check the debug log, looking for ReadUserLog or FileModifiedTrigger.  (Or call htcondor.enable_debug() and try again.) but just a single line with one of running,success,failed is expected.
Full Traceback (most recent call last):
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 886, in _wait_thread
    asyncio.run(self._wait_for_jobs())
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 1379, in _wait_for_jobs
    status = job_status(active_job)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/site-packages/snakemake/executors/__init__.py", line 1349, in job_status
    raise WorkflowError(
snakemake.exceptions.WorkflowError: Cluster status command .profiles/lxbatch/grid-status.py returned failed: JobEventLog not initialized.  Check the debug log, looking for ReadUserLog or FileModifiedTrigger.  (Or call htcondor.enable_debug() and try again.) but just a single line with one of running,success,failed is expected.

WorkflowError:
Cluster status command .profiles/lxbatch/grid-status.py returned failed: JobEventLog not initialized.  Check the debug log, looking for ReadUserLog or FileModifiedTrigger.  (Or call htcondor.enable_debug() and try again.) but just a single line with one of running,success,failed is expected.
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/asyncio/runners.py", line 190, in run
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/asyncio/runners.py", line 118, in run
  File "/afs/cern.ch/work/f/feickert/snakemake-lxplus-example/.pixi/envs/default/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-04-05T021318.611270.snakemake.log
```

</details>

I'm using `snakemake` `v7.32.4` given Issue https://github.com/Snakemake-Profiles/htcondor/issues/18

```console
$ pixi list | grep 'snakemake\|htcondor'
htcondor-classads          23.5.3        h1bc8f3f_0           10.4 MiB    conda  htcondor-classads-23.5.3-h1bc8f3f_0.conda
python-htcondor            23.5.3        py311h01e4ee6_0      9.4 MiB     conda  python-htcondor-23.5.3-py311h01e4ee6_0.conda
snakemake                  7.32.4        hdfd78af_1           8.7 KiB     conda  snakemake-7.32.4-hdfd78af_1.tar.bz2
snakemake-minimal          7.32.4        pyhdfd78af_1         271.6 KiB   conda  snakemake-minimal-7.32.4-pyhdfd78af_1.tar.bz2
$ condor_version
$CondorVersion: 23.0.2 2023-11-20 BuildID: 690948 PackageID: 23.0.2-1 $
$CondorPlatform: x86_64_AlmaLinux9 $
```

**Comment by jheuel** [comment]
I just tested it with your setup, found the same error and confirmed that adding the authentication lines to `grid-submit.py` solves the problem. You may also want to move the log directory to your AFS work space because we do not have a lot of space in our home directories.

**Comment by matthewfeickert** [comment]
Thanks @jheuel. That indeed works.

Would you be open to a PR that adds a `use_kerberos` option to [`cookiecutter.json`](https://github.com/Snakemake-Profiles/htcondor/blob/fd097135bf3336248ed259e142ee22a7a974c729/cookiecutter.json) that if

```
use_kerberos=True
```

will add

```python
# add kerberos credentials
col = htcondor.Collector()
credd = htcondor.Credd()
credd.add_user_cred(htcondor.CredTypes.Kerberos, None)
sub["MY.SendCredential"] = "True"
```

to the `grid-submit.py` file?

**Comment by jheuel** [comment]
Sure, but please call it something like `use_cern` because it is only how the CERN batch system implements authentication.
